apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
          listen       8096;
          root   /var/www/html;
          index  index.html index.htm index.php;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: nginx-phpfpm
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 8096
      volumeMounts:
        - mountPath: "/var/www/html"
          name: shared-files
        - name: nginx-config-volume
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
    - name: php-fpm-container
      image: php:8.2-fpm-alpine
      volumeMounts:
        - mountPath: "/var/www/html"
          name: shared-files
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm-service
spec:
  type: NodePort
  selector:
    app: nginx-phpfpm
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30012