apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: media
  containers:
    - name: secret-container-xfusion
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep infinity"]
      volumeMounts:
        - name: secret-volume
          mountPath: "/opt/cluster"